stages:
  - 初始化
  - 构建
  - 提审

初始化:
  stage: 初始化
  script:
   - echo "Build Proj"
   - gem install fastlane -NV

  only:
  - develop
  tags:
  - Mac
  # - SuZhou-Mac


同步证书:
  stage: 初始化
  script:
    - echo "Try to match cer"
    - fastlane syncCer
  when: manual
  only:
  - develop
  tags:
  # - Mac
  - SuZhou-Mac

构建-SIT:
  stage: 构建
  script:
    - echo "Start pack SIT"
    - fastlane sit
  when: manual
  only:
  - develop
  tags:
  # - Mac
  - SuZhou-Mac

构建-UAT:
  stage: 构建
  script:
    - echo "Start pack UAT"
    - fastlane uat
  when: manual
  only:
  - develop
  tags:
  # - Mac
  - SuZhou-Mac

构建-PRO:
  stage: 构建
  script:
    - pod install
    - echo "Start pack PRO"
    - fastlane pro
  when: manual
  only:
  - develop
  tags:
  # - Mac
  - SuZhou-Mac

提审:
  stage: 提审
  script:
    - echo "Start pack PRO"
    - fastlane dep
  when: manual
  only:
  - develop
  tags:
  # - Mac
  - SuZhou-Mac
